=== gkurtar/dlxml/Config/DLXML_Config.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="Configuration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Files">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="RuleFiles">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="File" maxOccurs="unbounded">
											
											<xsd:complexType>
												<xsd:attribute name="Name" type="xsd:normalizedString" use="required"/>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="SchemaFile" type="xsd:normalizedString" use="required"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Vocabulary">
								<xsd:complexType>
									<xsd:attribute name="Name" type="xsd:normalizedString" use="required"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="InputStreamSchema">
								<xsd:complexType>
									<xsd:attribute name="Name" type="xsd:normalizedString" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<!--
						<xsd:attribute name="DirectoryURL" type="xsd:normalizedString" use="required"/> 
						 -->
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Parameters">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Param" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="Key" type="xsd:normalizedString" use="required"/>
									<xsd:attribute name="Value" type="xsd:normalizedString" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
			</xsd:sequence>	
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== gkurtar/dlxml/Config/DLXML_Config.xml
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
					xsi:noNamespaceSchemaLocation="DLXML_Config.xsd">
	
	<!-- <Files  DirectoryURL="./Config/"  > -->
	<Files>
		<RuleFiles SchemaFile="DataLinkGrammar.xsd">
			<File Name="Link11_M1_Rule.xml"/>
			<File Name="Link11_M81_Rule.xml"/>
			<File Name="Link11_M2_Rule.xml"/>
			<File Name="Link11_M82_Rule.xml"/>
			<File Name="Link11_M6B_Rule.xml"/>
			<File Name="Link11_M86B_Rule.xml"/>
			<File Name="Link11_M3_Rule.xml"/>
			<File Name="Link11_M83_Rule.xml"/>
			<File Name="Link11_M5_Rule.xml"/>
			<File Name="Link11_M85_Rule.xml"/>
			<File Name="Link11_M6C_Rule.xml"/>
			<File Name="Link11_M86C_Rule.xml"/>
			<File Name="Link11_M9D_Rule.xml"/>
			<File Name="Link11_M9E_Rule.xml"/>
			<File Name="Link11_M11D_Rule.xml"/>
			<File Name="Link11_M11M_Rule.xml"/>
			<File Name="Link11_M811M_Rule.xml"/>
			<File Name="Link11_M12_31_Rule.xml"/>
			<File Name="Link11_M15_Rule.xml"/>
		</RuleFiles>
		<Vocabulary Name="Vocabulary.xml"/>
		<InputStreamSchema Name="InputDataGrammar.xsd"/>
	</Files>
	
	<Parameters>
		<Param Key="ValidateInputStreams" Value="false"/>
		<!--  <ValidateInputStreams>false</ValidateInputStreams> -->
	</Parameters>

</Configuration>
